# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='email_address',
            field=models.EmailField(max_length=254, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='location',
            field=models.CharField(choices=[('New York, NY', 'NY'), ('Chicago', 'CH'), ('Dallas, TX', 'DA'), ('LosAngeles, CA', 'LA')], max_length=20),
        ),
    ]
